### ISSUE TITLE
maxout_out fails for prototype_test

### ISSUE THREAD

**Issue by julianser** [sordonia/hed-dlg#15]
When I set maxout_out = True for prototype_test Theano crashes because of an inconsistency between weight sizes. The prototype_moviedic works fine with maxout_out though...

The bug happens in the latest version of the code, but I think the exact same thing will happen in the older versions of the code. This is the error message I get:

Traceback (most recent call last):
  File "train.py", line 550, in <module>
    main(args)
  File "train.py", line 196, in main
    samples, costs = random_sampler.sample([[]], n_samples=1, n_turns=3)
  File "/home/julian/UdeM/Projects/Dialog/Github/hed-dlg/search.py", line 47, in sample_apply
    samples, costs = sample_logic(sampler, joined_context, **kwargs) 
  File "/home/julian/UdeM/Projects/Dialog/Github/hed-dlg/search.py", line 168, in sample
    next_probs, new_hd = self.next_probs_predictor(prev_hs, prev_words, prev_hd)
  File "/home/julian/Theano/Theano/theano/compile/function_module.py", line 599, in **call**
    outputs = self.fn()
  File "/home/julian/Theano/Theano/theano/gof/link.py", line 526, in streamline_default_f
    raise_with_op(node, thunk)
  File "/home/julian/Theano/Theano/theano/gof/link.py", line 522, in streamline_default_f
    thunk()
  File "/home/julian/Theano/Theano/theano/gof/op.py", line 759, in rval
    r = p(n, [x[0] for x in i], o)
  File "/home/julian/Theano/Theano/theano/tensor/blas.py", line 1653, in perform
    z[0] = numpy.asarray(numpy.dot(x, y))
ValueError: ('shapes (1,25) and (10,17) not aligned: 25 (dim 1) != 10 (dim 0)', (1, 25), (10, 17))
Apply node that caused the error: Dot22(max, Wd_emb.T)
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(1, 25), (10, 17)]
Inputs strides: [(100, 4), (4, 40)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by sordonia** [comment]
This is not a bug, in order to use maxout,
we need to have rankdim = qdim / 2,
if you set rankdim = 25 in your test prototype
it should work !
